### NUMPY
**Numpy is Multi Dimensional Array Liberary**

**list**                                

1. slow                             
2. different types                  
3. insertion,deletion,concatenation,appending,etc
---
**numpy**
1. fast
2. fixed types
3. insertion,deletion,concatenation,appending,etc
---
1. numpy is faster to read less bytes of memory
2. no type checking when iterating through object
3. numpy use contiguous memory so all 8 blocks are right next to each other 

---
**benefits:**
1. SIMD(single info multiple data) vector processing
2. effective cache checking
---
**application:**
1. mathematics (MATLAB replacement)
2. plotting (matplotlib)
3. backend (pandas,connect 4,digital photography)
4. machine learning


In [1]:
import numpy as np

In [ ]:
# basic 

a = np.array([[1,2,3,4,5],[2,3,5,6,8]],dtype='int32')
b = np.array([5,6,7,8,9])

print(a*b)
print(a.ndim)
print(a.shape)
print(a.dtype)      
print(a.itemsize)   # 2 = int16 , 4 = int32 , 8 = int64

print(a.size * a.itemsize)
print(a.nbytes)                      # total size 



[[ 5 12 21 32 45]
 [10 18 35 48 72]]
2
(2, 5)
int64
8
80
80


In [44]:
# accessing / changing specific elements,row,column,etc

print(a[1,3])    # [row index  , column index ]
print(a[0,:])     # specific row
print(a[:,3])     # specific column 
print(a[0,1:-1:2])  # [ row , intial index : final index : step size (index 1 + 2 = index 3 )]
print(a[:,:3])  

a[1,3] =13        # insert at a fixed index
print(a)

a[:,4] = 7
print(a)

a[:,:3] = [12,23,34]
print(a)

13
[ 7  7  7 12  7]
[12 13]
[ 7 12]
[[7 7 7]
 [7 7 7]]
[[ 7  7  7 12  7]
 [ 7  7  7 13  7]]
[[ 7  7  7 12  7]
 [ 7  7  7 13  7]]
[[12 23 34 12  7]
 [12 23 34 13  7]]


In [52]:
# 3D array         
p = np.array([[[1,2,23,4,5],[4,5,23,5,6]],[[4,5,23,5,6],[24,234,23,56,2]],[[1,2,23,4,5],[4,5,23,5,6]]]) 
print(p.shape)      # [NO. of matrixs, each matrix row , each matrix column  ]

print(p[0,1,2])
print(p[:,1,:])

(3, 2, 5)
23
[[  4   5  23   5   6]
 [ 24 234  23  56   2]
 [  4   5  23   5   6]]
