 # access modifier

In [11]:
class arya:
    def __init__(self,name,age,gen):
        self.name=name
        self._age=age
        self.__gen=gen
    
class ved():
    pass

o1 = arya("yash",12,"male")
o2 = ved()
print(o2.name)

dir(o1)


AttributeError: 'ved' object has no attribute 'name'

In [ ]:
class Arya:
    def __init__(self, name, age):
        self.name = name  # Public attribute
        self.age = age    # Public attribute
    
    def display(self):  # Public method
        return f"Name: {self.name}, Age: {self.age}"

# Accessing public members in another class
class Ved:
    def show(self, obj):
        print(f"Accessing from Ved: {obj.name}, {obj.age}")

# Accessing public members in a function
def print_details(obj):
    print(f"Accessing from function: {obj.name}, {obj.age}")

# Creating an object of Arya
o1 = Arya("Yash", 20)

# Accessing from another class
o2 = Ved()
o2.show(o1)

# Accessing from a function
print_details(o1)

# Accessing directly
print(o1.name)
print(o1.age)
print(o1.display())


In [ ]:
import numpy as np
lst= list(range(1,50))
arr = np.array(lst)
print(type(arr))

print(lst)

<class 'numpy.ndarray'>
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]


In [20]:


arr1= np.array([[[1,2,3],[1,54,6],[3,3,7]],[[1,56,2],[53,75,77],[53,87,54]]])
print(arr1)

[[[ 1  2  3]
  [ 1 54  6]
  [ 3  3  7]]

 [[ 1 56  2]
  [53 75 77]
  [53 87 54]]]


In [ ]:
arr2 = np.ones((3,4))
print(arr2)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1.]]
