In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('Used_Bikes.csv')

In [3]:
df

bike_name     price       city  kms_driven  \
0        TVS Star City Plus Dual Tone 110cc   35000.0  Ahmedabad     17654.0   
1               Royal Enfield Classic 350cc  119900.0      Delhi     11000.0   
2                      Triumph Daytona 675R  600000.0      Delhi       110.0   
3                      TVS Apache RTR 180cc   65000.0  Bangalore     16329.0   
4      Yamaha FZ S V 2.0 150cc-Ltd. Edition   80000.0  Bangalore     10000.0   
...                                     ...       ...        ...         ...   
32643                Hero Passion Pro 100cc   39000.0      Delhi     22000.0   
32644                  TVS Apache RTR 180cc   30000.0     Karnal      6639.0   
32645              Bajaj Avenger Street 220   60000.0      Delhi     20373.0   
32646             Hero Super Splendor 125cc   15600.0     Jaipur     84186.0   
32647                    Bajaj Pulsar 150cc   22000.0       Pune     60857.0   

             owner   age  power          brand  
0      First Owner   3.0  110.0            TVS  
1      First Owner   4.0  350.0  Royal Enfield  
2      First Owner   8.0  675.0        Triumph  
3      First Owner   4.0  180.0            TVS  
4      First Owner   3.0  150.0         Yamaha  
...            ...   ...    ...            ...  
32643  First Owner   4.0  100.0           Hero  
32644  First Owner   9.0  180.0            TVS  
32645  First Owner   6.0  220.0          Bajaj  
32646  First Owner  16.0  125.0           Hero  
32647  First Owner  13.0  150.0          Bajaj  

[32648 rows x 8 columns]

In [4]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...  
32643     True
32644     True
32645     True
32646     True
32647     True
Length: 32648, dtype: bool

In [5]:
df.isnull().sum()

bike_name     0
price         0
city          0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [6]:
df.drop_duplicates(inplace=True)

In [7]:
df['city'].unique()

array(['Ahmedabad', 'Delhi', 'Bangalore', 'Mumbai', 'Kalyan', 'Faridabad',
       'Mettur', 'Hyderabad', 'Kaithal', 'Gurgaon', 'Pune', 'Noida',
       'Nashik', 'Kochi', 'Allahabad', 'Samastipur', 'Nadiad', 'Lucknow',
       'Jaipur', 'Karnal', 'Gorakhpur', 'Vidisha', 'Hosur', 'Bagalkot',
       'Baripara', 'Agra', 'Dharwad', 'Vadodara', 'Jalandhar', 'Surat',
       'Chennai', 'Navi Mumbai', 'Gandhidham', 'Visakhapatnam',
       'Thrissur', 'Kolkata', 'Ernakulam', 'Barasat', 'Ghaziabad',
       'Bhubaneshwar', 'Amritsar', 'Bhopal', 'Hamirpur(hp)', 'Kottayam',
       'Arrah', 'Patiala', 'Ranga Reddy', 'Mandi', 'Ludhiana', 'Mandya',
       'Siliguri', 'Aurangabad', 'Kanpur', 'Bhilwara', 'Meerut', 'Rewari',
       'Ahmednagar', 'Wardha', 'Chandigarh', 'Ranchi', 'Panvel', 'Thane',
       'Jabalpur', 'Kota', 'Rohtak', 'Rajkot', 'Varanasi', '24 Pargana',
       'Banka', 'Nagpur', 'Banki', 'Pali', 'Chhatarpur', 'Katihar',
       'Mohali', 'Rudrapur', 'Coimbatore', 'Jajpur', 'Mysore', 'Adoni',

In [8]:
df['bike_name'].unique()

array(['TVS Star City Plus Dual Tone 110cc',
       'Royal Enfield Classic 350cc', 'Triumph Daytona 675R',
       'TVS Apache RTR 180cc', 'Yamaha FZ S V 2.0 150cc-Ltd. Edition',
       'Yamaha FZs 150cc', 'Honda CB Hornet 160R  ABS DLX',
       'Hero Splendor Plus Self Alloy 100cc',
       'Royal Enfield Thunderbird X 350cc',
       'Royal Enfield Classic Desert Storm 500cc',
       'Yamaha YZF-R15 2.0 150cc', 'Yamaha FZ25 250cc',
       'Bajaj Pulsar NS200', 'Bajaj Discover 100M', 'Bajaj Discover 125M',
       'Bajaj Pulsar NS200 ABS', 'Bajaj Pulsar RS200 ABS',
       'Suzuki Gixxer SF 150cc', 'Benelli 302R 300CC',
       'Hero Splendor iSmart Plus IBS 110cc',
       'Royal Enfield Classic Chrome 500cc', 'Yamaha FZ V 2.0 150cc',
       'Hero Super Splendor 125cc', 'Honda CBF Stunner 125cc',
       'Bajaj Pulsar 150cc', 'Honda X-Blade 160CC ABS',
       'Bajaj Avenger 220cc', 'KTM RC 390cc', 'Honda CB Unicorn 150cc',
       'KTM Duke 200cc', 'Honda CBR 150R 150cc',
       'Royal Enfiel

In [9]:
df['brand'].unique()

array(['TVS', 'Royal Enfield', 'Triumph', 'Yamaha', 'Honda', 'Hero',
       'Bajaj', 'Suzuki', 'Benelli', 'KTM', 'Mahindra', 'Kawasaki',
       'Ducati', 'Hyosung', 'Harley-Davidson', 'Jawa', 'BMW', 'Indian',
       'Rajdoot', 'LML', 'Yezdi', 'MV', 'Ideal'], dtype=object)

In [10]:
df['owner'].unique()

array(['First Owner', 'Second Owner', 'Third Owner',
       'Fourth Owner Or More'], dtype=object)

In [11]:
df.drop(['bike_name','city'],axis=1,inplace=True)

In [12]:
df

price  kms_driven        owner  age  power            brand
0      35000.0     17654.0  First Owner  3.0  110.0              TVS
1     119900.0     11000.0  First Owner  4.0  350.0    Royal Enfield
2     600000.0       110.0  First Owner  8.0  675.0          Triumph
3      65000.0     16329.0  First Owner  4.0  180.0              TVS
4      80000.0     10000.0  First Owner  3.0  150.0           Yamaha
...        ...         ...          ...  ...    ...              ...
9362   25000.0     48587.0  First Owner  8.0  150.0             Hero
9369   35000.0     60000.0  First Owner  9.0  220.0            Bajaj
9370  450000.0      3430.0  First Owner  4.0  750.0  Harley-Davidson
9371  139000.0     21300.0  First Owner  4.0  400.0            Bajaj
9372   80000.0      7127.0  First Owner  5.0  220.0            Bajaj

[7324 rows x 6 columns]

In [13]:
dt={
    'First Owner':1,
    'Second Owner':2,
    'Third Owner':3,
    'Fourth Owner Or More':4
}
df['owner']=df['owner'].map(dt)

In [14]:
df['owner'].unique()

array([1, 2, 3, 4])

In [15]:
df

price  kms_driven  owner  age  power            brand
0      35000.0     17654.0      1  3.0  110.0              TVS
1     119900.0     11000.0      1  4.0  350.0    Royal Enfield
2     600000.0       110.0      1  8.0  675.0          Triumph
3      65000.0     16329.0      1  4.0  180.0              TVS
4      80000.0     10000.0      1  3.0  150.0           Yamaha
...        ...         ...    ...  ...    ...              ...
9362   25000.0     48587.0      1  8.0  150.0             Hero
9369   35000.0     60000.0      1  9.0  220.0            Bajaj
9370  450000.0      3430.0      1  4.0  750.0  Harley-Davidson
9371  139000.0     21300.0      1  4.0  400.0            Bajaj
9372   80000.0      7127.0      1  5.0  220.0            Bajaj

[7324 rows x 6 columns]

In [16]:
pip install sklearn

  Using cached sklearn-0.0.post12.tar.gz (2.6 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
Note: you may need to restart the kernel to use updated packages.


  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.
      
      Here is how to fix this error in the main use cases:
      - use 'pip install scikit-learn' rather than 'pip install sklearn'
      - replace 'sklearn' by 'scikit-learn' in your pip requirements files
        (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
      - if the 'sklearn' package is used by one of your dependencies,
        it would be great if you take some time to track which package uses
        'sklearn' instead of 'scikit-learn' and report it to their issue tracker
      - as a last resort, set the environment variable
        SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error
      
      More information is available at
      https://github.com/scikit-learn/sklearn-

In [17]:
pip install scikit-learn

In [18]:
import sklearn as sk

In [19]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [20]:
encoder=LabelEncoder()

In [21]:
output=encoder.fit_transform(df['brand'])

In [22]:
# output.classes_

In [23]:
output

array([19, 17, 20, ...,  4,  1,  1], shape=(7324,))

In [24]:
df['brand']=output

In [25]:
output.shape

(7324,)

In [26]:
df.dtypes

price         float64
kms_driven    float64
owner           int64
age           float64
power         float64
brand           int64
dtype: object

In [27]:
x=df.drop('price',axis=1)
y=df[['price']]

In [28]:
x

kms_driven  owner  age  power  brand
0        17654.0      1  3.0  110.0     19
1        11000.0      1  4.0  350.0     17
2          110.0      1  8.0  675.0     20
3        16329.0      1  4.0  180.0     19
4        10000.0      1  3.0  150.0     21
...          ...    ...  ...    ...    ...
9362     48587.0      1  8.0  150.0      5
9369     60000.0      1  9.0  220.0      1
9370      3430.0      1  4.0  750.0      4
9371     21300.0      1  4.0  400.0      1
9372      7127.0      1  5.0  220.0      1

[7324 rows x 5 columns]

In [29]:
y

price
0      35000.0
1     119900.0
2     600000.0
3      65000.0
4      80000.0
...        ...
9362   25000.0
9369   35000.0
9370  450000.0
9371  139000.0
9372   80000.0

[7324 rows x 1 columns]

In [30]:
df

price  kms_driven  owner  age  power  brand
0      35000.0     17654.0      1  3.0  110.0     19
1     119900.0     11000.0      1  4.0  350.0     17
2     600000.0       110.0      1  8.0  675.0     20
3      65000.0     16329.0      1  4.0  180.0     19
4      80000.0     10000.0      1  3.0  150.0     21
...        ...         ...    ...  ...    ...    ...
9362   25000.0     48587.0      1  8.0  150.0      5
9369   35000.0     60000.0      1  9.0  220.0      1
9370  450000.0      3430.0      1  4.0  750.0      4
9371  139000.0     21300.0      1  4.0  400.0      1
9372   80000.0      7127.0      1  5.0  220.0      1

[7324 rows x 6 columns]

In [31]:
from sklearn.model_selection import train_test_split

In [32]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [33]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((5859, 5), (1465, 5), (5859, 1), (1465, 1))

In [34]:
x_train.head()
x_train.shape 

(5859, 5)

In [35]:
y_train.head()
y_train.shape

(5859, 1)

In [36]:
#from sklearn.linear_model import LinearRegression
from sklearn.ensemble import GradientBoostingRegressor

In [37]:
#lr =LinearRegression()
gb=GradientBoostingRegressor()

In [38]:
x_train.isnull()

kms_driven  owner    age  power  brand
5789       False  False  False  False  False
3451       False  False  False  False  False
735        False  False  False  False  False
7533       False  False  False  False  False
8461       False  False  False  False  False
...          ...    ...    ...    ...    ...
6522       False  False  False  False  False
6583       False  False  False  False  False
6856       False  False  False  False  False
1028       False  False  False  False  False
9250       False  False  False  False  False

[5859 rows x 5 columns]

In [39]:
#lr.fit(x_train,y_train)
gb.fit(x_train,y_train)

d:\code\python\venv\Lib\site-packages\sklearn\ensemble\_gb.py:672: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?


GradientBoostingRegressor()

In [40]:
#print ("Testing Score:",lr.score(x_test,y_test))
print("Testing Score is:",gb.score(x_test,y_test))

Testing Score is: 0.8993324380798964


In [41]:
#lr.predict(x_test)
gb.predict(x_test)

array([ 99941.2040897 , 144231.52264847,  60970.51445021, ...,
        63161.10342403, 110946.69816322,  64010.45172761], shape=(1465,))

In [42]:
#pred=lr.predict(x_test)
pred=gb.predict(x_test)

In [43]:
pred

array([ 99941.2040897 , 144231.52264847,  60970.51445021, ...,
        63161.10342403, 110946.69816322,  64010.45172761], shape=(1465,))

In [44]:
x_test.shape

(1465, 5)

In [45]:
y_test['pred']=pred

In [46]:
y_test

price           pred
4909   88400.0   99941.204090
1942  102850.0  144231.522648
5763   67000.0   60970.514450
4800   30000.0   32997.551411
7614   20000.0   20601.623628
...        ...            ...
5653  395000.0  425461.752069
609   140000.0  153705.064510
4211   54500.0   63161.103424
6379  114000.0  110946.698163
647    36000.0   64010.451728

[1465 rows x 2 columns]

In [47]:
df

price  kms_driven  owner  age  power  brand
0      35000.0     17654.0      1  3.0  110.0     19
1     119900.0     11000.0      1  4.0  350.0     17
2     600000.0       110.0      1  8.0  675.0     20
3      65000.0     16329.0      1  4.0  180.0     19
4      80000.0     10000.0      1  3.0  150.0     21
...        ...         ...    ...  ...    ...    ...
9362   25000.0     48587.0      1  8.0  150.0      5
9369   35000.0     60000.0      1  9.0  220.0      1
9370  450000.0      3430.0      1  4.0  750.0      4
9371  139000.0     21300.0      1  4.0  400.0      1
9372   80000.0      7127.0      1  5.0  220.0      1

[7324 rows x 6 columns]

In [48]:
import joblib as jb

#loss function
MSE
MAE
RMSE
Huber loss

###MSE

In [49]:
from sklearn.metrics import mean_squared_error,mean_absolute_error

In [50]:
y_test.drop('pred',axis=1,inplace=True)

In [51]:
print("mse:-",mean_squared_error(y_test,pred))

mse:- 1959868273.5866203


In [52]:
# pred ,y_test #actual #predicted

In [53]:
print("mae:-",mean_absolute_error(y_test,pred))

mae:- 15903.460966959736


RMSE

In [54]:
from sklearn.metrics import mean_squared_error
import math
import numpy as np

In [55]:
print("RMSE:-",math.sqrt(mean_squared_error(y_test,pred)))

RMSE:- 44270.39951916653


In [56]:
print('by using numpy:-',math.sqrt(mean_squared_error(y_test,pred)))

by using numpy:- 44270.39951916653


In [57]:
y_test

price
4909   88400.0
1942  102850.0
5763   67000.0
4800   30000.0
7614   20000.0
...        ...
5653  395000.0
609   140000.0
4211   54500.0
6379  114000.0
647    36000.0

[1465 rows x 1 columns]

Huber Loss

#Model Evaluation
confusion matrix
accuracy
precision
Recall
F1 Score

In [58]:
from sklearn.metrics import confusion_matrix,f1_score,precision_score,recall_score

In [59]:
pred=(pred>0.5).astype(int).ravel()

In [60]:
confusion_matrix(y_test,pred)

array([[0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [2, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]], shape=(419, 419))

In [61]:
#print("precision:-",precision_score(y_test,pred))
#print("precision score:-",precision_score(y_test,pred))
#print("recall score",recall_score(y_test,pred))
#print("F1 score:",f1_score(y_test,pred))

In [62]:
import  matplotlib.pyplot as plt
import seaborn as sns

In [63]:
cm=confusion_matrix(y_test,pred)

In [64]:
cm

array([[0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [2, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]], shape=(419, 419))

In [65]:
#sns.heatmap(cm,annot=True,cmap='Blues',fmt='d')
#plt.title('confusion matrix')


In [66]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor

In [67]:
obj=RandomForestClassifier()

In [68]:
obj=RandomForestRegressor()

In [69]:
obj.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'criterion': 'squared_error',
 'max_depth': None,
 'max_features': 1.0,
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [71]:
import xgboost as xgb

In [72]:
from sklearn.datasets import load_breast_cancer

In [73]:
x,y=load_breast_cancer(return_X_y=True)

In [74]:
from sklearn.model_selection import train_test_split

In [75]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [76]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((455, 30), (114, 30), (455,), (114,))

In [77]:
model_xg=xgb.XGBClassifier()

In [78]:
model_xg.fit(x_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)